spring.application.name=todo

spring.config.import=optional:file:.env[.properties]
#Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
spring.datasource.username=postgres
spring.datasource.password=Dinhchuong123456

#Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Server Port
server.port=8080

#auth
spring.security.user.name=admin
spring.security.user.password=password123

#JWT
jwt.secret=9SD8F7S9D8798SHBDTGF9JHOI34JO4NM5O236E3272357538782F413F4PQ2N90H
jwt.expiration=86400000